import React from 'react';
// import styles from './styles.scss';

const Hero = () => (
  <div id="hero">
    <p>Hero</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales arcu eget ante ultrices, et faucibus ligula maximus. Proin tincidunt ipsum nec nibh ornare fringilla. Sed posuere aliquam erat, quis posuere eros ullamcorper dignissim. In vitae diam porta est condimentum venenatis ut interdum dolor. Vestibulum tellus sapien, semper posuere dapibus sit amet, faucibus eu nunc. Etiam malesuada tincidunt mollis. Suspendisse ullamcorper tempor purus id malesuada. Phasellus hendrerit magna eu nulla pellentesque, a tristique mauris mollis. Curabitur blandit vel mi in luctus. Sed sagittis nulla non bibendum consectetur. Phasellus accumsan mattis dolor, eget egestas nisl egestas iaculis. Sed porta luctus sem, at suscipit ligula euismod commodo. Donec vel metus metus. Proin elementum velit nulla, eget volutpat ex fringilla sit amet.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales arcu eget ante ultrices, et faucibus ligula maximus. Proin tincidunt ipsum nec nibh ornare fringilla. Sed posuere aliquam erat, quis posuere eros ullamcorper dignissim. In vitae diam porta est condimentum venenatis ut interdum dolor. Vestibulum tellus sapien, semper posuere dapibus sit amet, faucibus eu nunc. Etiam malesuada tincidunt mollis. Suspendisse ullamcorper tempor purus id malesuada. Phasellus hendrerit magna eu nulla pellentesque, a tristique mauris mollis. Curabitur blandit vel mi in luctus. Sed sagittis nulla non bibendum consectetur. Phasellus accumsan mattis dolor, eget egestas nisl egestas iaculis. Sed porta luctus sem, at suscipit ligula euismod commodo. Donec vel metus metus. Proin elementum velit nulla, eget volutpat ex fringilla sit amet.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales arcu eget ante ultrices, et faucibus ligula maximus. Proin tincidunt ipsum nec nibh ornare fringilla. Sed posuere aliquam erat, quis posuere eros ullamcorper dignissim. In vitae diam porta est condimentum venenatis ut interdum dolor. Vestibulum tellus sapien, semper posuere dapibus sit amet, faucibus eu nunc. Etiam malesuada tincidunt mollis. Suspendisse ullamcorper tempor purus id malesuada. Phasellus hendrerit magna eu nulla pellentesque, a tristique mauris mollis. Curabitur blandit vel mi in luctus. Sed sagittis nulla non bibendum consectetur. Phasellus accumsan mattis dolor, eget egestas nisl egestas iaculis. Sed porta luctus sem, at suscipit ligula euismod commodo. Donec vel metus metus. Proin elementum velit nulla, eget volutpat ex fringilla sit amet.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales arcu eget ante ultrices, et faucibus ligula maximus. Proin tincidunt ipsum nec nibh ornare fringilla. Sed posuere aliquam erat, quis posuere eros ullamcorper dignissim. In vitae diam porta est condimentum venenatis ut interdum dolor. Vestibulum tellus sapien, semper posuere dapibus sit amet, faucibus eu nunc. Etiam malesuada tincidunt mollis. Suspendisse ullamcorper tempor purus id malesuada. Phasellus hendrerit magna eu nulla pellentesque, a tristique mauris mollis. Curabitur blandit vel mi in luctus. Sed sagittis nulla non bibendum consectetur. Phasellus accumsan mattis dolor, eget egestas nisl egestas iaculis. Sed porta luctus sem, at suscipit ligula euismod commodo. Donec vel metus metus. Proin elementum velit nulla, eget volutpat ex fringilla sit amet.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales arcu eget ante ultrices, et faucibus ligula maximus. Proin tincidunt ipsum nec nibh ornare fringilla. Sed posuere aliquam erat, quis posuere eros ullamcorper dignissim. In vitae diam porta est condimentum venenatis ut interdum dolor. Vestibulum tellus sapien, semper posuere dapibus sit amet, faucibus eu nunc. Etiam malesuada tincidunt mollis. Suspendisse ullamcorper tempor purus id malesuada. Phasellus hendrerit magna eu nulla pellentesque, a tristique mauris mollis. Curabitur blandit vel mi in luctus. Sed sagittis nulla non bibendum consectetur. Phasellus accumsan mattis dolor, eget egestas nisl egestas iaculis. Sed porta luctus sem, at suscipit ligula euismod commodo. Donec vel metus metus. Proin elementum velit nulla, eget volutpat ex fringilla sit amet.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales arcu eget ante ultrices, et faucibus ligula maximus. Proin tincidunt ipsum nec nibh ornare fringilla. Sed posuere aliquam erat, quis posuere eros ullamcorper dignissim. In vitae diam porta est condimentum venenatis ut interdum dolor. Vestibulum tellus sapien, semper posuere dapibus sit amet, faucibus eu nunc. Etiam malesuada tincidunt mollis. Suspendisse ullamcorper tempor purus id malesuada. Phasellus hendrerit magna eu nulla pellentesque, a tristique mauris mollis. Curabitur blandit vel mi in luctus. Sed sagittis nulla non bibendum consectetur. Phasellus accumsan mattis dolor, eget egestas nisl egestas iaculis. Sed porta luctus sem, at suscipit ligula euismod commodo. Donec vel metus metus. Proin elementum velit nulla, eget volutpat ex fringilla sit amet.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales arcu eget ante ultrices, et faucibus ligula maximus. Proin tincidunt ipsum nec nibh ornare fringilla. Sed posuere aliquam erat, quis posuere eros ullamcorper dignissim. In vitae diam porta est condimentum venenatis ut interdum dolor. Vestibulum tellus sapien, semper posuere dapibus sit amet, faucibus eu nunc. Etiam malesuada tincidunt mollis. Suspendisse ullamcorper tempor purus id malesuada. Phasellus hendrerit magna eu nulla pellentesque, a tristique mauris mollis. Curabitur blandit vel mi in luctus. Sed sagittis nulla non bibendum consectetur. Phasellus accumsan mattis dolor, eget egestas nisl egestas iaculis. Sed porta luctus sem, at suscipit ligula euismod commodo. Donec vel metus metus. Proin elementum velit nulla, eget volutpat ex fringilla sit amet.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales arcu eget ante ultrices, et faucibus ligula maximus. Proin tincidunt ipsum nec nibh ornare fringilla. Sed posuere aliquam erat, quis posuere eros ullamcorper dignissim. In vitae diam porta est condimentum venenatis ut interdum dolor. Vestibulum tellus sapien, semper posuere dapibus sit amet, faucibus eu nunc. Etiam malesuada tincidunt mollis. Suspendisse ullamcorper tempor purus id malesuada. Phasellus hendrerit magna eu nulla pellentesque, a tristique mauris mollis. Curabitur blandit vel mi in luctus. Sed sagittis nulla non bibendum consectetur. Phasellus accumsan mattis dolor, eget egestas nisl egestas iaculis. Sed porta luctus sem, at suscipit ligula euismod commodo. Donec vel metus metus. Proin elementum velit nulla, eget volutpat ex fringilla sit amet.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales arcu eget ante ultrices, et faucibus ligula maximus. Proin tincidunt ipsum nec nibh ornare fringilla. Sed posuere aliquam erat, quis posuere eros ullamcorper dignissim. In vitae diam porta est condimentum venenatis ut interdum dolor. Vestibulum tellus sapien, semper posuere dapibus sit amet, faucibus eu nunc. Etiam malesuada tincidunt mollis. Suspendisse ullamcorper tempor purus id malesuada. Phasellus hendrerit magna eu nulla pellentesque, a tristique mauris mollis. Curabitur blandit vel mi in luctus. Sed sagittis nulla non bibendum consectetur. Phasellus accumsan mattis dolor, eget egestas nisl egestas iaculis. Sed porta luctus sem, at suscipit ligula euismod commodo. Donec vel metus metus. Proin elementum velit nulla, eget volutpat ex fringilla sit amet.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales arcu eget ante ultrices, et faucibus ligula maximus. Proin tincidunt ipsum nec nibh ornare fringilla. Sed posuere aliquam erat, quis posuere eros ullamcorper dignissim. In vitae diam porta est condimentum venenatis ut interdum dolor. Vestibulum tellus sapien, semper posuere dapibus sit amet, faucibus eu nunc. Etiam malesuada tincidunt mollis. Suspendisse ullamcorper tempor purus id malesuada. Phasellus hendrerit magna eu nulla pellentesque, a tristique mauris mollis. Curabitur blandit vel mi in luctus. Sed sagittis nulla non bibendum consectetur. Phasellus accumsan mattis dolor, eget egestas nisl egestas iaculis. Sed porta luctus sem, at suscipit ligula euismod commodo. Donec vel metus metus. Proin elementum velit nulla, eget volutpat ex fringilla sit amet.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales arcu eget ante ultrices, et faucibus ligula maximus. Proin tincidunt ipsum nec nibh ornare fringilla. Sed posuere aliquam erat, quis posuere eros ullamcorper dignissim. In vitae diam porta est condimentum venenatis ut interdum dolor. Vestibulum tellus sapien, semper posuere dapibus sit amet, faucibus eu nunc. Etiam malesuada tincidunt mollis. Suspendisse ullamcorper tempor purus id malesuada. Phasellus hendrerit magna eu nulla pellentesque, a tristique mauris mollis. Curabitur blandit vel mi in luctus. Sed sagittis nulla non bibendum consectetur. Phasellus accumsan mattis dolor, eget egestas nisl egestas iaculis. Sed porta luctus sem, at suscipit ligula euismod commodo. Donec vel metus metus. Proin elementum velit nulla, eget volutpat ex fringilla sit amet.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sodales arcu eget ante ultrices, et faucibus ligula maximus. Proin tincidunt ipsum nec nibh ornare fringilla. Sed posuere aliquam erat, quis posuere eros ullamcorper dignissim. In vitae diam porta est condimentum venenatis ut interdum dolor. Vestibulum tellus sapien, semper posuere dapibus sit amet, faucibus eu nunc. Etiam malesuada tincidunt mollis. Suspendisse ullamcorper tempor purus id malesuada. Phasellus hendrerit magna eu nulla pellentesque, a tristique mauris mollis. Curabitur blandit vel mi in luctus. Sed sagittis nulla non bibendum consectetur. Phasellus accumsan mattis dolor, eget egestas nisl egestas iaculis. Sed porta luctus sem, at suscipit ligula euismod commodo. Donec vel metus metus. Proin elementum velit nulla, eget volutpat ex fringilla sit amet.</p>
  </div>
);

export default Hero;
